(ns monero-store.contract-test
  "The contract spine itself: that every function has one, that they are
  ENFORCED while the suite runs, and that the schemas have teeth.

  Loading this namespace instruments the whole store. Every other test in the
  suite therefore runs against instrumented functions, so a schema that lies
  about its own function fails here rather than being decoration."
  (:require [clojure.java.io :as io]
            [clojure.string :as str]
            [clojure.test :refer [deftest is testing]]
            [hive-schemas.test :as hst]
            [malli.core :as m]
            [malli.instrument :as mi]
            [monero-store.collect.analytics :as analytics]
            [monero-store.currency :as currency]
            [monero-store.payments.chain]
            [monero-store.promote.invoice :as invoice]
            [monero-store.promote.quote :as quote]
            [monero-store.schema :as schema]))

(defn- source-namespaces
  "Every namespace under src/, read off disk rather than listed by hand."
  []
  (->> (file-seq (io/file "src"))
       (filter #(and (.isFile ^java.io.File %)
                     (str/ends-with? (.getName ^java.io.File %) ".clj")))
       (map #(-> (.getPath ^java.io.File %)
                 (str/replace #"^src/" "")
                 (str/replace #"\.clj$" "")
                 (str/replace "_" "-")
                 (str/replace "/" ".")
                 symbol))
       sort))

(run! require (source-namespaces))

(mi/instrument!)

;; ---------------------------------------------------------------------------
;; coverage

(def store-namespaces
  "Every namespace of the store itself.

  `monero-store.adt` is excluded: its functions are generated by `defadt` from
  the sum declaration, so there is no form to attach a contract to and the
  generated malli schema already describes the values."
  (->> (all-ns)
       (map ns-name)
       (filter #(re-find #"^monero-store\." (str %)))
       (remove #(re-find #"-test$" (str %)))
       (remove #{'monero-store.adt 'monero-store.support})
       sort))

(defn- contracted-fns
  "[contracted uncontracted] var names in `ns-sym`.

  A protocol method is not a function this namespace defines — it dispatches to
  whatever implements it — so it carries no contract of its own."
  [ns-sym]
  (let [declared (set (keys (get (m/function-schemas) ns-sym)))
        candidates (->> (ns-interns ns-sym)
                        (filter (fn [[_ v]]
                                  (let [meta' (meta v)]
                                    (and (fn? @v)
                                         (not (:macro meta'))
                                         (not (:protocol meta'))))))
                        (map key)
                        set)]
    [(sort (filter declared candidates))
     (sort (remove declared candidates))]))

(deftest every-namespace-in-the-store-loads
  (let [found (source-namespaces)]
    (testing "the walk finds the store, not an empty directory"
      (is (< 20 (count found))))

    (testing "and every one of them is loaded, so the guards below can see it"
      (is (= [] (remove (set (map ns-name (all-ns))) found))))

    (testing "the entry namespace included — it is the one nothing else requires"
      (is (contains? (set found) 'monero-store.system)))))

(deftest every-function-in-the-store-declares-its-contract
  (let [missing (into {}
                      (keep (fn [ns-sym]
                              (let [[_ uncontracted] (contracted-fns ns-sym)]
                                (when (seq uncontracted) [ns-sym (vec uncontracted)]))))
                      store-namespaces)]
    (testing "a new function without an m/=> is a hole in the spine, so it fails here"
      (is (= {} missing)))
    (testing "and the spine is not empty, which is the failure this guard could hide"
      (is (< 100 (reduce + (map (comp count first contracted-fns) store-namespaces)))))))

;; ---------------------------------------------------------------------------
;; enforcement

(deftest the-contracts-are-instrumented-not-merely-declared
  (testing "a wrong argument type is caught at the call, not deep inside"
    (is (thrown? clojure.lang.ExceptionInfo (currency/->display :xmr "1000")))
    (is (thrown? clojure.lang.ExceptionInfo (currency/known? "xmr"))))

  (testing "and the right one still passes straight through"
    (is (= "0.001000000000" (currency/->display :xmr 1000000000)))
    (is (true? (currency/known? :xmr)))))

(deftest the-schemas-name-real-values
  (testing "every registered function schema compiles"
    (doseq [[ns-sym fns] (m/function-schemas)
            :when (re-find #"^monero-store\." (str ns-sym))
            [fn-sym {:keys [schema]}] fns]
      (is (some? (m/form schema)) (str ns-sym "/" fn-sym)))))

;; ---------------------------------------------------------------------------
;; synthesized from the schemas
;;
;; The generator, the oracle and the mutants all come from the same schemas the
;; contracts are written in — nothing below is a hand-written case.

(hst/deftrifecta-from-schema display-is-total
  monero-store.currency/->display
  {:in [:cat [:enum :xmr :btc :usd :eur :brl] [:int {:min 0 :max 1000000000000}]]
   :out schema/NonBlank
   :rel (fn [[currency-id amount] out]
          (and (string? out)
               (if (pos? (currency/scale currency-id))
                 (re-find #"\." out)
                 (not (re-find #"\." out)))
               (or (pos? amount) (re-find #"^0" out))))
   :mutation false
   :num-tests 200})

(hst/deftrifecta-from-schema median-is-a-middle
  monero-store.promote.quote/median
  {:in [:vector {:min 1 :max 12} [:double {:min 0.01 :max 100000.0}]]
   :out [:maybe number?]
   :rel (fn [xs out]
          (and (<= (apply min xs) (double out))
               (<= (double out) (apply max xs))))
   :mutation false
   :num-tests 200})

(hst/deftrifecta-from-schema scrubbing-only-ever-removes
  monero-store.collect.analytics/scrub
  {:in [:map-of :keyword [:or :string :int :boolean]]
   :out [:map-of :keyword :any]
   :rel (fn [props out]
          (and (<= (count out) (count props))
               (empty? (filter #{:email :address :tx-hash :reference :secret :token}
                               (keys out)))))
   :mutation false
   :num-tests 200})

(def PlausibleObservation
  "A WalletObservation whose amounts a chain could actually carry.

  The production schema says `[:int {:min 0}]`, and it is right to: an amount
  is a non-negative integer of atomic units and the wallet is the authority on
  it. But a generator reading that schema literally will mint transfers of
  9.2e18 piconero each and sum them past Long/MAX — an arithmetic overflow that
  is real, and that no wallet on a chain with a 1.8e19 supply cap can produce.
  The bound belongs to the generator, not to the contract."
  [:map {:closed true}
   [:wallet/address schema/NonBlank]
   [:wallet/transfers
    [:sequential {:max 6}
     [:map {:closed true}
      [:transfer/tx-hash schema/NonBlank]
      [:transfer/amount [:int {:min 0 :max 1000000000000000}]]
      [:transfer/confirmations [:int {:min 0 :max 1000}]]
      [:transfer/locked? :boolean]
      [:transfer/double-spend? :boolean]]]]
   [:wallet/unlocked-amount {:optional true} [:maybe [:int {:min 0 :max 1000000000000000}]]]])

;; The one output shape closed enough to mutate: hive-test corrupts the
;; Settlement schema and every corruption must be caught, which is what proves
;; the schema is a specification rather than a description.
(hst/deftrifecta-from-schema settlement-never-credits-a-double-spend
  monero-store.payments.chain/settlement-of
  {:in [:cat :keyword PlausibleObservation [:int {:min 0 :max 1000000000}]]
   :out schema/Settlement
   :rel (fn [[provider-id observation expected] out]
          (let [honest (remove :transfer/double-spend? (:wallet/transfers observation))]
            (and (= provider-id (:settlement/provider out))
                 (= expected (:settlement/expected-amount out))
                 (<= (:settlement/paid-amount out)
                     (reduce + 0 (map :transfer/amount honest))))))
   :mutation true
   :num-tests 100})

(def fixed-instant
  "One clock reading, so a generated rate is fresh by construction and the
  property is about agreement rather than about staleness."
  (java.util.Date. 1700000000000))

(def agreeing-profile
  {:quote/min-sources 2
   :quote/max-age-ms 3600000
   :quote/max-spread-bps 5000})

(hst/deftrifecta-from-schema consensus-never-invents-a-price
  monero-store.promote.quote/consensus
  {:in [:cat
        [:enum {} agreeing-profile]
        [:sequential {:min 2 :max 6}
         [:map {:closed true}
          [:rate/source [:enum :alpha :beta :gamma :delta]]
          [:rate/pair [:enum {} [:xmr :usd]]]
          [:rate/price [:double {:min 100.0 :max 110.0}]]
          [:rate/as-of [:enum {} fixed-instant]]]]
        [:enum {} [:xmr :usd]]
        [:enum {} fixed-instant]]
   :out [:map {:closed true}
         [:rate/price number?]
         [:rate/sources [:vector :keyword]]]
   :rel (fn [[_ rates _ _] out]
          (let [prices (map :rate/price rates)]
            (and (<= (apply min prices) (:rate/price out) (apply max prices))
                 (<= 2 (count (:rate/sources out)))
                 (every? (set (map :rate/source rates)) (:rate/sources out)))))
   :mutation true
   :num-tests 200})

(def GeneratedInvoice
  "An invoice, GENERATED.

  `schema/Invoice` is the contract and validates one; it cannot generate one,
  because `Instant` is `[:fn inst?]` and a predicate has no generator. So this
  is a tuple of the two things the property varies — the status, and how far
  the expiry sits either side of the clock — fmapped into a real invoice. The
  value handed to the subject still satisfies `schema/Invoice`, which the live
  instrumentation checks on every call."
  [:tuple {:gen/fmap (fn [[status offset-ms]]
                       {:invoice/id (random-uuid)
                        :invoice/customer-id (random-uuid)
                        :invoice/item-id :pro
                        :invoice/provider :monero
                        :invoice/status status
                        :invoice/amount 1000
                        :invoice/currency :xmr
                        :invoice/external-ref nil
                        :invoice/expires-at (java.util.Date.
                                             (+ (.getTime fixed-instant) offset-ms))
                        :invoice/created-at fixed-instant})}
   [:enum :pending :paid :underpaid :expired :failed]
   [:int {:min -600000 :max 600000}]])

(hst/deftrifecta-from-schema money-is-never-applied-to-a-closed-invoice
  monero-store.promote.invoice/resolution
  {:in [:cat GeneratedInvoice [:enum {} fixed-instant]]
   :out [:enum :applied :late]
   :rel (fn [[invoice now] out]
          (= out (if (and (invoice/open? invoice) (not (invoice/lapsed? invoice now)))
                   :applied
                   :late)))
   :mutation false
   :num-tests 200})

(deftest a-forbidden-key-never-survives-scrubbing
  (testing "the property above generates keys at random; this states the ones that matter"
    (doseq [k [:email :customer-id :address :pay-to :external-ref :reference :tx-hash :secret :token]]
      (is (= {} (analytics/scrub {k "sensitive"})) (str k " reached an analytics sink")))))
